export const enEmoji = {
  A: ['🍎 Apple', '✈️ Airplane', '🐜 Ant', '👨‍🚀 Astronaut', '🐊 Alligator'],
  B: ['🍌 Banana', '🐻 Bear', '🎈 Balloon', '🥦 Broccoli', '🦋 Butterfly'],
  C: ['🐱 Cat', '🍪 Cookie', '🤡 Clown', '🚗 Car', '🍰 Cake'],
  D: ['🐕 Dog', '🦌 Deer', '🎲 Dice', '🐬 Dolphin', '🦆 Duck'],
  E: ['🥚 Egg', '🐘 Elephant', '👁️ Eye', '🦅 Eagle', '🌍 Earth'],
  F: ['🐟 Fish', '🦊 Fox', '🔥 Fire', '🌸 Flower', '🐸 Frog'],
  G: ['🦒 Giraffe', '🍇 Grapes', '🎸 Guitar', '👻 Ghost', '🐐 Goat'],
  H: ['🏠 House', '🐎 Horse', '🎩 Hat', '🦛 Hippo', '🔨 Hammer'],
  I: ['🍦 Ice Cream', '🦎 Iguana', '🏝️ Island', '🛖 Igloo', '🖋️ Ink'],
  J: ['🤹 Juggler', '🎶 Jazz', '🪼 Jellyfish', '🏺 Jar', '🚙 Jeep'],
  K: ['🪁 Kite', '🔑 Key', '👑 King', '🐨 Koala', '🥝 Kiwi'],
  L: ['🦁 Lion', '🍃 Leaf', '💡 Light', '🍋 Lemon', '🐞 Ladybug'],
  M: ['🌙 Moon', '🐒 Monkey', '🎵 Music', '🐭 Mouse', '🥛 Milk'],
  N: ['👃 Nose', '📰 Newspaper', '🌙 Night', '🪹 Nest', '🕸️ Net'],
  O: ['🐙 Octopus', '🍊 Orange', '🦉 Owl', '🧅 Onion', '🌊 Ocean'],
  P: ['🐼 Panda', '🖊️ Pen', '🍕 Pizza', '🐷 Pig', '🐧 Penguin'],
  Q: ['👸 Queen', '🪡 Quilt', '❓ Question', '🐦 Quail', '🤫 Quiet'],
  R: ['🌹 Rose', '🎀 Ribbon', '🚀 Rocket', '🐰 Rabbit', '🌧️ Rain'],
  S: ['🌞 Sun', '⭐ Star', '🐍 Snake', '😊 Smile', '🕷️ Spider'],
  T: ['🐯 Tiger', '🌳 Tree', '🚂 Train', '🐢 Turtle', '🍅 Tomato'],
  U: ['☂️ Umbrella', '🦄 Unicorn', '👆 Up', '⬇️ Under', '👨‍🦳 Uncle'],
  V: ['🎻 Violin', '🌋 Volcano', '🚐 Van', '🏺 Vase', '🥦 Vegetable'],
  W: ['🐺 Wolf', '💧 Water', '🌊 Wave', '🐋 Whale', '⌚ Watch'],
  X: ['🪕 Xylophone', '🦴 X-ray', '❌ X-mark', '🧪 Xenon', '📠 Xerox'],
  Y: ['🟡 Yellow', '🧒 Youth', '☯️ Yin-yang', '🪀 Yo-yo', '🐃 Yak'],
  Z: ['🦓 Zebra', '🤐 Zipper', '⚡ Zigzag', '🦁 Zoo', '0️⃣ Zero']
}

export const idEmoji = {
  A: ['🍎 Apel', '🥑 Alpukat', '🍇 Anggur', '🪿 Angsa', '🚑 Ambulans', '🔥 Api'],
  B: ['🦆 Bebek', '🐻 Beruang', '🎈 Balon', '🥦 Brokoli', '🪨 Batu', '⭐️ Bintang'],
  C: ['😣 Cemas', '🍫 Coklat', '🌶️ Cabai', '🍒 Ceri', '👖 Celana', '💍 Cincin'],
  D: ['🐑 Domba', '🎲 Dadu', '🍩 Donat', '🍖 Daging', '🥁 Drum'],
  E: ['🦅 Elang', '🍦 Es Krim', '🪣 Ember', '🔥 Elpiji', '🐕 Ekor'],
  F: ['🦩 Flamingo', '📸 Foto', '🦴 Fosil', '🚢 Feri', '🎞️ Film'],
  G: ['🐘 Gajah', '🦍 Gorila', '🎸 Gitar', '⛪️ Gereja', '🦷 Gigi', '🗻 Gunung'],
  H: ['🐯 Harimau', '🐹 Hamster', '👃 Hidung', '🦈 Hiu', '🚁 Helikopter', '📱 Handphone'],
  I: ['🐟 Ikan', '🦎 Iguana', '🇮🇩 Indonesia', '🦆 Itik', '💎 Intan'],
  J: ['🦒 Jerapah', '🦗 Jangkrik', '🍊 Jeruk', '🍄 Jamur', '⌚️ Jam'],
  K: ['🐸 Katak', '🦘 Kanguru', '🐱 Kucing', '🕋 Kabah', '🌵 Kaktus', '☕️ Kopi'],
  L: ['🐝 Lebah', '🕷️ Laba-laba', '🪰 Lalat', '👅 Lidah', '🔔 Lonceng', '🕯️ Lilin'],
  M: ['🐒 Monyet', '🌹 Mawar', '🕌 Masjid', '👄 Mulut', '🥭 Mangga'],
  N: ['🐉 Naga', '🦟 Nyamuk', '🦜 Nuri', '🍍 Nanas', '🍈 Nangka'],
  O: ['🦧 Orang Utan', '🦦 Otter', '🪛 Obeng', '🌊 Ombak', '💊 Obat'],
  P: ['🫁 Paru-paru', '🐼 Panda', '☂️ Payung', '🍌 Pisang', '🍕 Pizza'],
  Q: ['📖 Quran', '👳 Qari', '🧕 Qoriah', '📶 Quota', '🕌 Qasar'],
  R: ['🦌 Rusa', '🍞 Roti', '🦊 Rubah', '🏠 Rumah', '🛞 Roda'],
  S: ['🦁 Singa', '🐮 Sapi', '🐜 Semut', '🍉 Semangka', '🍓 Stroberi', '👟 Sepatu'],
  T: ['🐭 Tikus', '🐿️ Tupai', '🦴 Tulang', '🍅 Tomat', '🎾 Tenis', '🧢 Topi'],
  U: ['🪼 Ubur-ubur', '🐍 Ular', '🦐 Udang', '💵 Uang', '🐪 Unta'],
  V: ['🧛 Vampir', '🏺 Vas', '📹 Video', '🏡 Vila', '🗣️ Vokal'],
  W: ['🥕 Wortel', '🍳 Wajan', '🎭 Wayang', '🏖️ Wisata', '👩 Wanita'],
  X: ['🎹 Xilofon', '🧪 Xenon', '📠 Xerografi', '⚗️ Xylol', '🩻 Sinar-X'],
  Y: ['🪀 Yoyo', '✅ Yakin', '🏢 Yayasan', '👦 Yatim', '🧘 Yoga'],
  Z: ['🦓 Zebra', '🫒 Zaitun', '💎 Zamrud', '⏳ Zaman', '💰 Zakat']
}