export const enEmoji = {
  A: ['🍎 Apple', '✈️ Airplane', '🐜 Ant'],
  B: ['🍌 Banana', '🐻 Bear', '🎈 Balloon', '🥦 Broccoli'],
  C: ['🐱 Cat', '🍪 Cookie', '🤡 Clown'],
  D: ['🐕 Dog', '🦌 Deer', '🎲 Dice'],
  E: ['🥚 Egg', '🐘 Elephant', '👁️ Eye'],
  F: ['🐟 Fish', '🦊 Fox', '🔥 Fire'],
  G: ['🦒 Giraffe', '🍇 Grapes', '🎸 Guitar'],
  H: ['🏠 House', '🐎 Horse', '🎩 Hat'],
  I: ['🍦 Ice Cream', '🦎 Iguana', '🏝️ Island'],
  J: ['🤹 Juggler', '🎸 Jazz', '🦘 Kangaroo'],
  K: ['🪁 Kite', '🔑 Key', '👑 King'],
  L: ['🦁 Lion', '🍃 Leaf', '💡 Light'],
  M: ['🌙 Moon', '🐒 Monkey', '🎵 Music'],
  N: ['👃 Nose', '📰 Newspaper', '🌙 Night'],
  O: ['🐙 Octopus', '🍊 Orange', '🦉 Owl'],
  P: ['🐼 Panda', '🖊️ Pen', '🍕 Pizza'],
  Q: ['👸 Queen', '🪆 Quilt', '❓ Question'],
  R: ['🌹 Rose', '🎀 Ribbon', '🚀 Rocket'],
  S: ['🌞 Sun', '⭐ Star', '🐍 Snake', '😊 Smile'],
  T: ['🐯 Tiger', '🌳 Tree', '🚂 Train'],
  U: ['☂️ Umbrella', '🦄 Unicorn', '👆 Up'],
  V: ['🎻 Violin', '🌋 Volcano', '🚐 Van', '🏺 Vas'],
  W: ['🐺 Wolf', '💧 Water', '🌊 Wave'],
  X: ['📦 Box', '🎸 Xylophone', '❌ X-mark'],
  Y: ['🟡 Yellow', '🧒 Youth', '☯️ Yin-yang'],
  Z: ['🦓 Zebra', '🤐 Zipper', '⚡ Zigzag']
}

export const idEmoji = {
  A: ['🍎 Apel', '🥑 Alpukat',  '🍇 Anggur', '🪿 Angsa', '🚑 Ambulans', '🔥 Api'],
  B: ['🦆 Bebek', '🐻 Beruang', '🎈 Balon', '🥦 Brokoli', '🪨 Batu', '⭐️ Bintang'],
  C: ['😣 Cemas', '🍫 Coklat', '🌶️ Cabai', '🍒 Ceri', '👖 Celana', '💍 Cincin'],
  D: ['🐑 Domba', '🎲 Dadu', '🍩 Donat', '🍖 Daging', '🥁 Drum'],
  E: ['🦅 Elang', '🍦 Es Krim'],
  F: ['🦩 Flamingo'],
  G: ['🐘 Gajah', '🦍 Gorila', '🎸 Gitar', '⛪️ Gereja', '🦷 Gigi', '🗻 Gunung'],
  H: ['🐯 Harimau', '🐹 Hamster', '👃 Hidung', '🦈 Hiu', '🚁 Helikopter', '📱 Handphone'],
  I: ['🐟 Ikan', '🦎 Iguana', '🇮🇩 Indonesia'],
  J: ['🦒 Jerapah', '🦗 Jangkrik', '🍊 Jeruk', '🍄 Jamur', '⌚️ Jam'],
  K: ['🐸 Katak', '🦘 Kanguru', '🐱 Kucing', '🕋 Kabah', '🌵 Kaktus', '☕️ Kopi'],
  L: ['🦁 Lebah', '🕷️ Laba-laba', '🪰 Lalat', '👅 Lidah', '🔔 Lonceng', '🕯️ Lilin'],
  M: ['🐒 Monyet', '🌹 Mawar', '🕌 Masjid', '👄 Mulut', '🥭 Mangga'],
  N: ['🐉 Naga', '🦟 Nyamuk', '🦜 Nuri', '🍍 Nanas'],
  O: ['🦧 Orang Utan', '🦦 Otter', '🪛 Obeng'],
  P: ['🫁 Paru-paru', '🐼 Panda', '☂️ Payung', '🍌 Pisang', '🍕 Pizza'],
  Q: ['🐜 Qilin'],
  R: ['🦌 Rusa', '🍞 Roti', '🦊 Rubah', '🏠 Rumah', '🛞 Roda'],
  S: ['🦁 Singa', '🐮 Sapi', '🐜 Semut', '🍉 Semangka', '🍓 Stroberi', '👟 Sepatu'],
  T: ['🐭 Tikus', '🐿️ Tupai', '🦴 Tulang', '🍅 Tomat', '🎾 Tenis', '🧢 Topi'],
  U: ['🪼 Ubur-ubur', '🐍 Ular', '🦐 Udang', '💵 Uang'],
  V: ['🧛 Vampir', '🏺 Vas'],
  W: ['🥕 Wortel'],
  X: ['❌ Tidak ada kata dalam bahasa Indonesia yang dimulai dengan X'],
  Y: ['🪀 Yoyo'],
  Z: ['🦓 Zebra']
}