export const enEmoji = {
  A: ['🍎 Apple', '✈️ Airplane', '🐜 Ant', '👨‍🚀 Astronaut', '🐊 Alligator'],
  B: ['🍌 Banana', '🐻 Bear', '🎈 Balloon', '🥦 Broccoli', '🦋 Butterfly'],
  C: ['🐱 Cat', '🍪 Cookie', '🤡 Clown', '🚗 Car', '🍰 Cake'],
  D: ['🐕 Dog', '🦌 Deer', '🎲 Dice', '🐬 Dolphin', '🦆 Duck'],
  E: ['🥚 Egg', '🐘 Elephant', '👁️ Eye', '🦅 Eagle', '🌍 Earth'],
  F: ['🐟 Fish', '🦊 Fox', '🔥 Fire', '🌸 Flower', '🐸 Frog'],
  G: ['🦒 Giraffe', '🍇 Grapes', '🎸 Guitar', '👻 Ghost', '🐐 Goat'],
  H: ['🏠 House', '🐎 Horse', '🎩 Hat', '🦛 Hippo', '🔨 Hammer'],
  I: ['🍦 Ice Cream', '🦎 Iguana', '🏝️ Island', '🛖 Igloo', '🖋️ Ink'],
  J: ['🤹 Juggler', '🎶 Jazz', '🪼 Jellyfish', '🏺 Jar', '🚙 Jeep'],
  K: ['🪁 Kite', '🔑 Key', '👑 King', '🐨 Koala', '🥝 Kiwi'],
  L: ['🦁 Lion', '🍃 Leaf', '💡 Light', '🍋 Lemon', '🐞 Ladybug'],
  M: ['🌙 Moon', '🐒 Monkey', '🎵 Music', '🐭 Mouse', '🥛 Milk'],
  N: ['👃 Nose', '📰 Newspaper', '🌙 Night', '🪹 Nest', '🕸️ Net'],
  O: ['🐙 Octopus', '🍊 Orange', '🦉 Owl', '🧅 Onion', '🌊 Ocean'],
  P: ['🐼 Panda', '🖊️ Pen', '🍕 Pizza', '🐷 Pig', '🐧 Penguin'],
  Q: ['👸 Queen', '🪡 Quilt', '❓ Question', '🐦 Quail', '🤫 Quiet'],
  R: ['🌹 Rose', '🎀 Ribbon', '🚀 Rocket', '🐰 Rabbit', '🌧️ Rain'],
  S: ['🌞 Sun', '⭐ Star', '🐍 Snake', '😊 Smile', '🕷️ Spider'],
  T: ['🐯 Tiger', '🌳 Tree', '🚂 Train', '🐢 Turtle', '🍅 Tomato'],
  U: ['☂️ Umbrella', '🦄 Unicorn', '👆 Up', '⬇️ Under', '👨‍🦳 Uncle'],
  V: ['🎻 Violin', '🌋 Volcano', '🚐 Van', '🏺 Vase', '🥦 Vegetable'],
  W: ['🐺 Wolf', '💧 Water', '🌊 Wave', '🐋 Whale', '⌚ Watch'],
  X: ['🪕 Xylophone', '🦴 X-ray', '❌ X-mark', '🧪 Xenon', '📠 Xerox'],
  Y: ['🟡 Yellow', '🧒 Youth', '☯️ Yin-yang', '🪀 Yo-yo', '🐃 Yak'],
  Z: ['🦓 Zebra', '🤐 Zipper', '⚡ Zigzag', '🦁 Zoo', '0️⃣ Zero']
}

export const idEmoji = {
  A: ['🍎 Apel', '🥑 Alpukat', '🍇 Anggur', '🪿 Angsa', '🚑 Ambulans', '🔥 Api'],
  B: ['🦆 Bebek', '🐻 Beruang', '🎈 Balon', '🥦 Brokoli', '🪨 Batu', '⭐️ Bintang'],
  C: ['😣 Cemas', '🍫 Coklat', '🌶️ Cabai', '🍒 Ceri', '👖 Celana', '💍 Cincin'],
  D: ['🐑 Domba', '🎲 Dadu', '🍩 Donat', '🍖 Daging', '🥁 Drum'],
  E: ['🦅 Elang', '🍦 Es Krim', '🪣 Ember', '🔥 Elpiji', '🐕 Ekor'],
  F: ['🦩 Flamingo', '📸 Foto', '🦴 Fosil', '🚢 Feri', '🎞️ Film'],
  G: ['🐘 Gajah', '🦍 Gorila', '🎸 Gitar', '⛪️ Gereja', '🦷 Gigi', '🗻 Gunung'],
  H: ['🐯 Harimau', '🐹 Hamster', '👃 Hidung', '🦈 Hiu', '🚁 Helikopter', '📱 Handphone'],
  I: ['🐟 Ikan', '🦎 Iguana', '🇮🇩 Indonesia', '🦆 Itik', '💎 Intan'],
  J: ['🦒 Jerapah', '🦗 Jangkrik', '🍊 Jeruk', '🍄 Jamur', '⌚️ Jam'],
  K: ['🐸 Katak', '🦘 Kanguru', '🐱 Kucing', '🕋 Kabah', '🌵 Kaktus', '☕️ Kopi'],
  L: ['🐝 Lebah', '🕷️ Laba-laba', '🪰 Lalat', '👅 Lidah', '🔔 Lonceng', '🕯️ Lilin'],
  M: ['🐒 Monyet', '🌹 Mawar', '🕌 Masjid', '👄 Mulut', '🥭 Mangga'],
  N: ['🐉 Naga', '🦟 Nyamuk', '🦜 Nuri', '🍍 Nanas', '🍈 Nangka'],
  O: ['🦧 Orang Utan', '🦦 Otter', '🪛 Obeng', '🌊 Ombak', '💊 Obat'],
  P: ['🫁 Paru-paru', '🐼 Panda', '☂️ Payung', '🍌 Pisang', '🍕 Pizza'],
  Q: ['📖 Quran', '👳 Qari', '🧕 Qoriah', '📶 Quota', '🕌 Qasar'],
  R: ['🦌 Rusa', '🍞 Roti', '🦊 Rubah', '🏠 Rumah', '🛞 Roda'],
  S: ['🦁 Singa', '🐮 Sapi', '🐜 Semut', '🍉 Semangka', '🍓 Stroberi', '👟 Sepatu'],
  T: ['🐭 Tikus', '🐿️ Tupai', '🦴 Tulang', '🍅 Tomat', '🎾 Tenis', '🧢 Topi'],
  U: ['🪼 Ubur-ubur', '🐍 Ular', '🦐 Udang', '💵 Uang', '🐪 Unta'],
  V: ['🧛 Vampir', '🏺 Vas', '📹 Video', '🏡 Vila', '🗣️ Vokal'],
  W: ['🥕 Wortel', '🍳 Wajan', '🎭 Wayang', '🏖️ Wisata', '👩 Wanita'],
  X: ['🎹 Xilofon', '🧪 Xenon', '📠 Xerografi', '⚗️ Xylol', '🩻 Sinar-X'],
  Y: ['🪀 Yoyo', '✅ Yakin', '🏢 Yayasan', '👦 Yatim', '🧘 Yoga'],
  Z: ['🦓 Zebra', '🫒 Zaitun', '💎 Zamrud', '⏳ Zaman', '💰 Zakat']
}

export const enSentences = [
  "An apple and an ant are on the airplane.",
  "The astronaut saw an alligator in space.",
  "A bear holding a balloon ate a banana.",
  "The butterfly sits on the broccoli.",
  "A cat and a clown are in the car.",
  "The cookie and the cake are delicious.",
  "A dog and a deer saw a dolphin.",
  "The duck plays with the dice.",
  "An elephant ate an egg on Earth.",
  "The eagle has a very sharp eye.",
  "A fox and a fish are near the fire.",
  "The frog jumped over the flower.",
  "A giraffe and a goat play the guitar.",
  "The ghost saw a bunch of grapes.",
  "A horse in the house wore a hat.",
  "The hippo hit the nail with a hammer.",
  "An iguana ate ice cream on the island.",
  "The ink in the jar is in the igloo.",
  "A juggler in a jeep listens to jazz.",
  "The jellyfish is in the glass jar.",
  "A king with a key flies a kite.",
  "The koala ate a green kiwi.",
  "A lion and a ladybug on a leaf.",
  "The lemon is next to the light.",
  "A monkey saw the moon and music.",
  "The mouse drank a glass of milk.",
  "A nose and a nest in the night.",
  "The newspaper is caught in the net.",
  "An octopus and an owl in the ocean.",
  "The orange and the onion are round.",
  "A panda ate pizza with a pig.",
  "The penguin uses a pen.",
  "A queen on a quilt asks a question.",
  "The quail is very quiet.",
  "A rabbit with a ribbon and a rose.",
  "The rocket goes up in the rain.",
  "A snake with a smile saw a star.",
  "The spider is under the sun.",
  "A tiger and a turtle by the tree.",
  "The train carries a big tomato.",
  "An umbrella and a unicorn are up.",
  "The uncle is under the tree.",
  "A violin and a vase in the van.",
  "The volcano is near the vegetable.",
  "A wolf drank water from the wave.",
  "The whale has a new watch.",
  "An x-ray of a xylophone.",
  "The x-mark is on the xerox machine.",
  "A yellow yak played with a yo-yo.",
  "The zebra has a zigzag zipper."
];

export const idSentences = [
  "Apel dan alpukat ada di dalam ambulans.",
  "Angsa dan anggur dekat api.",
  "Bebek dan beruang bermain balon.",
  "Bintang bersinar di atas batu dan brokoli.",
  "Ceri dan coklat di dalam celana.",
  "Cincin emas dipakai saat cemas.",
  "Domba dan dadu di atas drum.",
  "Donat dan daging sangat enak.",
  "Elang membawa ember ke elpiji.",
  "Ekor anjing itu sangat panjang.",
  "Flamingo merah di atas feri.",
  "Foto fosil di dalam film.",
  "Gajah dan gorila bermain gitar.",
  "Gigi putih saat naik gunung.",
  "Harimau dan hamster punya hidung.",
  "Hiu dan helikopter di dekat handphone.",
  "Ikan dan iguana ada di Indonesia.",
  "Itik berenang mencari intan.",
  "Jerapah dan jangkrik makan jeruk.",
  "Jam dinding di dekat jamur.",
  "Katak dan kanguru melihat kaktus.",
  "Kucing duduk di atas kabah.",
  "Lebah dan laba-laba di lidah.",
  "Lilin dan lonceng sangat terang.",
  "Monyet membawa mawar ke masjid.",
  "Mulut makan mangga manis.",
  "Naga dan nyamuk di pohon nanas.",
  "Burung nuri makan nangka.",
  "Orang utan dan otter melihat ombak.",
  "Obeng dan obat di pinggir laut.",
  "Panda membawa payung dan pisang.",
  "Pizza enak dimakan saat hujan.",
  "Qari membaca quran di masjid.",
  "Qoriah membayar zakat fitrah.",
  "Rusa makan roti di rubah.",
  "Rumah itu punya roda besar.",
  "Singa dan sapi makan semangka.",
  "Sepatu baru untuk makan stroberi.",
  "Tikus dan tupai makan tomat.",
  "Topi biru di dekat tulang.",
  "Ubur-ubur dan ular di air.",
  "Udang dan unta bawa uang.",
  "Vampir duduk di dekat vas.",
  "Vila itu punya vokal bagus.",
  "Wortel dan wajan milik wanita.",
  "Wayang kulit di tempat wisata.",
  "Xilofon dan xenon di sinar-x.",
  "Xerografi dan xylol sangat unik.",
  "Yoyo dimainkan oleh anak yatim.",
  "Yayasan itu sangat yakin."
];